name: CD Gitops

on:
  push:
    branches: [ main ]  # Corrected capitalization for consistency

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Assuming your image name is 'gitopsfc' (replace if different)
          repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
          tags: 
            - ${{ github.sha }}  # Tag with commit SHA for version tracking
            - latest          # Latest tag for easy deployment

